apiVersion: apps/v1
kind: Deployment
metadata:
  name: managebook-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: managebook
  template:
    metadata:
      labels:
        app: managebook
    spec:
      containers:
      - name: managebook
        image: managebook:latest
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: managebook-service
spec:
  type: NodePort
  selector:
    app: managebook
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
